Update Jeninksfile

diff --git a/Jeninksfile b/Jeninksfile
--- a/Jeninksfile
+++ b/Jeninksfile
@@ -1,44 +1,68 @@
 pipeline {
-    agent any   // Run on any available agent
+    agent any
 
     tools {
-        maven 'Maven'   // Must match name configured in Jenkins (Global Tool Config)
+        maven 'Maven'
     }
 
     stages {
 
         stage('Checkout') {
             steps {
-                // Recommended if repo is configured in Jenkins
-                checkout scm
+                git branch: 'master',
+                url: 'https://github.com/Vachanbs/SeleniumChrome.git'
+            }
+        }
 
-                // OR use this if not configured:
-                git url: 'https://github.com/Vachanbs/SeleniumChrome.git', branch: 'master'
+        stage('Install Chrome & Dependencies') {
+            steps {
+                sh '''
+                echo "Checking Chrome..."
+
+                if ! command -v google-chrome > /dev/null
+                then
+                    echo "Installing Chrome..."
+                    sudo apt update
+                    sudo apt install -y wget unzip
+
+                    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+                    sudo apt install -y ./google-chrome-stable_current_amd64.deb
+                fi
+
+                echo "Chrome Version:"
+                google-chrome --version
+
+                echo "Installing required libraries..."
+                sudo apt-get install -y libxss1 libappindicator1 libindicator7 fonts-liberation libnss3 lsb-release xdg-utils
+                '''
             }
         }
 
         stage('Build') {
             steps {
-                sh 'mvn clean package'
+                sh 'mvn clean package -DskipTests'
             }
         }
 
-        stage('Test') {
+        stage('Run Application') {
             steps {
-                sh 'mvn test'
+                sh '''
+                echo "Files in target:"
+                ls -l target
+
+                echo "Running JAR..."
+                java -jar target/*.jar
+                '''
             }
         }
     }
 
     post {
-        always {
-            echo 'Pipeline execution completed'
-        }
         success {
-            echo 'Build SUCCESS ✅'
+            echo ' Build and execution SUCCESSFUL!'
         }
         failure {
-            echo 'Build FAILED ❌'
+            echo ' Build FAILED!'
         }
     }
 }
